@hostname=localhost
@port=8081

POST http://{{hostname}}}:{{port}}/auth/sign-up
Content-Type: application/json

{
  "username": "username",
  "password": "password",
  "email": "email@example.com"
}

###

POST http://{{hostname}}}:{{port}}/auth/sign-in
Content-Type: application/json

{
  "username": "username",
  "password": "password"
}