### Регистрация нового пользователя (успех)
POST http://localhost:8081/api/v1/signup
Content-Type: application/json

{
  "username": "newuser",
  "password": "securepassword123",
  "email": "newuser@example.com"
}

### Регистрация с отсутствующим именем пользователя
POST http://localhost:8081/api/v1/signup
Content-Type: application/json

{
  "password": "securepassword123",
  "email": "newuser@example.com"
}

### Регистрация с отсутствующим паролем
POST http://localhost:8081/api/v1/signup
Content-Type: application/json

{
  "username": "newuser",
  "email": "newuser@example.com"
}

### Регистрация с отсутствующим email
POST http://localhost:8081/api/v1/signup
Content-Type: application/json

{
  "username": "newuser",
  "password": "securepassword123"
}

### Регистрация с неверным форматом email
POST http://localhost:8081/api/v1/signup
Content-Type: application/json

{
  "username": "newuser",
  "password": "securepassword123",
  "email": "not-an-email"
}