// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username, password_hash, salt, email
) VALUES ($1, $2, $3, $3) RETURNING id, username, password_hash, salt, email, first_name, last_name, phone_number, date_of_birth, gender, bio, language_preference, created_at, updated_at, failed_login_attempts, is_verified
`

type CreateUserParams struct {
	Username     string `db:"username" json:"username"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
	Salt         string `db:"salt" json:"salt"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.PasswordHash, arg.Salt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Salt,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PhoneNumber,
		&i.DateOfBirth,
		&i.Gender,
		&i.Bio,
		&i.LanguagePreference,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailedLoginAttempts,
		&i.IsVerified,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, password_hash, salt FROM users
WHERE username = $1
`

type GetUserRow struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	PasswordHash string      `db:"password_hash" json:"password_hash"`
	Salt         string      `db:"salt" json:"salt"`
}

func (q *Queries) GetUser(ctx context.Context, username string) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, username)
	var i GetUserRow
	err := row.Scan(&i.ID, &i.PasswordHash, &i.Salt)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, username, password_hash, salt, email, first_name, last_name, phone_number, date_of_birth, gender, bio, language_preference, created_at, updated_at, failed_login_attempts, is_verified FROM users
WHERE id = $1 LIMIT  1
`

func (q *Queries) GetUserById(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Salt,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PhoneNumber,
		&i.DateOfBirth,
		&i.Gender,
		&i.Bio,
		&i.LanguagePreference,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailedLoginAttempts,
		&i.IsVerified,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, password_hash, salt, email, first_name, last_name, phone_number, date_of_birth, gender, bio, language_preference, created_at, updated_at, failed_login_attempts, is_verified FROM users
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.Salt,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.PhoneNumber,
			&i.DateOfBirth,
			&i.Gender,
			&i.Bio,
			&i.LanguagePreference,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FailedLoginAttempts,
			&i.IsVerified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
